### ISSUE TITLE
htmlroot with versionning files seems to fail.

### ISSUE THREAD

**Issue by guillaumebreux** [uncss/uncss#366]
Good morning :)

Instead of using a `rev` module to hash my assets files, I usually use for simple projects a easier way to do cache bursting by using: `?v=xxx` at the end of the path (i.e. `/assets/app.js?v=2`).

But I encounter this error when I use this technique with uncss: `Error: Could not load script: "file:///assets/app.js?v=2"` no matter the value of `htmlroot` (i really tried everything :D). But if I remove the `?v=2` everything works just fine.

Is this an expected behaviour?

**Comment by mikelambert** [comment]
Your OS filesystem appears not to understand web querystring semantics.
Which makes sense, since no OS filesystems do.

Yes, this is normal and expected. You should not use file:// and instead
host a small local proxy http:// server to seve off disk if you want to do
that.
2018年3月21日(水) 3:34 Guillaume <notifications@github.com>:

**Comment by guillaumebreux** [comment]
Interesting, that indeed makes sense.

I just stopped using this technique and start to rev my assets, that was better anyway :)

Thanks for this explanation
